### ISSUE TITLE
Fatal Error with Chests

### ISSUE THREAD

**Issue by Saphrym** [impiaaa/MyWorldGen#18]
I get the following when I try to use the loading wand to load in a schematic with a chest:

```
[18:15:46] [Client thread/INFO] [inventorytweaks]: net.boatcake.MyWorldGen.client.GuiLoadSchematic
[18:15:46] [Server thread/INFO]: Saving and pausing game...
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Underdark
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Erebus
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Spirit World
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/Torment
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/The Outer Lands
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/PocketDimension
[18:15:46] [Server thread/INFO]: Saving chunks for level 'New World'/SpectreWorld
[18:15:48] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
    at net.minecraft.enchantment.EnchantmentHelper.func_77513_b(EnchantmentHelper.java:358) ~[afv.class:?]
    at net.minecraft.enchantment.EnchantmentHelper.func_77504_a(EnchantmentHelper.java:316) ~[afv.class:?]
    at net.minecraft.item.ItemEnchantedBook.func_92112_a(SourceFile:116) ~[acm.class:?]
    at net.minecraft.item.Item.getChestGenBase(Item.java:1020) ~[adb.class:?]
    at net.minecraftforge.common.ChestGenHooks.getItems(ChestGenHooks.java:208) ~[ChestGenHooks.class:?]
    at net.boatcake.MyWorldGen.Schematic.placeInWorld(Schematic.java:490) ~[Schematic.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:51) ~[MessagePlaceSchem.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:19) ~[MessagePlaceSchem.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[18:15:48] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
    at net.minecraft.enchantment.EnchantmentHelper.func_77513_b(EnchantmentHelper.java:358) ~[afv.class:?]
    at net.minecraft.enchantment.EnchantmentHelper.func_77504_a(EnchantmentHelper.java:316) ~[afv.class:?]
    at net.minecraft.item.ItemEnchantedBook.func_92112_a(SourceFile:116) ~[acm.class:?]
    at net.minecraft.item.Item.getChestGenBase(Item.java:1020) ~[adb.class:?]
    at net.minecraftforge.common.ChestGenHooks.getItems(ChestGenHooks.java:208) ~[ChestGenHooks.class:?]
    at net.boatcake.MyWorldGen.Schematic.placeInWorld(Schematic.java:490) ~[Schematic.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:51) ~[MessagePlaceSchem.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:19) ~[MessagePlaceSchem.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[18:15:48] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel myworldgen
java.lang.NullPointerException
    at net.minecraft.enchantment.EnchantmentHelper.func_77513_b(EnchantmentHelper.java:358) ~[afv.class:?]
    at net.minecraft.enchantment.EnchantmentHelper.func_77504_a(EnchantmentHelper.java:316) ~[afv.class:?]
    at net.minecraft.item.ItemEnchantedBook.func_92112_a(SourceFile:116) ~[acm.class:?]
    at net.minecraft.item.Item.getChestGenBase(Item.java:1020) ~[adb.class:?]
    at net.minecraftforge.common.ChestGenHooks.getItems(ChestGenHooks.java:208) ~[ChestGenHooks.class:?]
    at net.boatcake.MyWorldGen.Schematic.placeInWorld(Schematic.java:490) ~[Schematic.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:51) ~[MessagePlaceSchem.class:?]
    at net.boatcake.MyWorldGen.network.MessagePlaceSchem.onMessage(MessagePlaceSchem.java:19) ~[MessagePlaceSchem.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[18:15:48] [Netty Client IO #4/INFO] [THAUMCRAFT]: Restoring client configs.
[18:15:48] [Netty Client IO #4/INFO] [MineMenu]: CLIENT: Disconnected from server, enabling all click actions
[18:15:48] [Netty Client IO #4/INFO] [simplyjetpacks]: Loading configuration files
[18:15:48] [Client thread/INFO] [journeymap]: Mapping halted in C:\Programs\MultiMC\instances\Industria Arcanum\minecraft\journeymap\data\sp\New World\DIM0
[18:15:48] [Server thread/INFO]: <PROFILE NAME> lost connection: TextComponent{text='A fatal error has occured, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:15:48] [Server thread/INFO]: <PROFILE NAME> left the game
[18:15:48] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:15:48] [Server thread/INFO] [PvpToggle]: Saving: [{"userName":"<PROFILE NAME>","hasPVP":false,"coolDown":0}]
[18:15:48] [Server thread/INFO]: Stopping server
[18:15:48] [Server thread/INFO]: Saving players
[18:15:48] [Server thread/INFO]: Saving worlds
[18:15:48] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/Underdark
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/Erebus
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/Spirit World
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/Torment
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/The Outer Lands
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/PocketDimension
[18:15:49] [Server thread/INFO]: Saving chunks for level 'New World'/SpectreWorld
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension 0
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension -1
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension 1
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension -100
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension 66
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension -37
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension -38
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension -42
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension 33
[18:15:49] [Server thread/INFO] [FML]: Unloading dimension 2
[18:15:51] [Server thread/INFO] [FML]: Applying holder lookups
[18:15:51] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[18:15:51] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[18:15:51] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[18:15:51] [Server thread/INFO] [FML]: Holder lookups applied
[18:15:51] [pool-5-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Trasciever data saved to C:\Programs\MultiMC\instances\Industria Arcanum\minecraft\saves\New World\enderio\dimensionalTransceiver.json
```

**Comment by Saphrym** [comment]
I have just confirmed it does NOT happen when spawned naturally.

**Comment by impiaaa** [comment]
Looks like this might be SEP, but it might be worth investigating to find who is at fault.
- What mods are you using?
- What version of MWG?
- What schematic were you trying to place?
- Did you select "Place as generated" or "Preserve anchors & chests"?

**Comment by Saphrym** [comment]
[ModList](https://github.com/MentatMinions/IndustriaArcanum/blob/ced109635d14d3949719377dac328a0b3bdd500f/MODLIST.md)
MWG 1.3.5
Any schematic with a chest... but just tried the mineshaft entrance and it did it again.
As Generated crashes... preserve does not.

**Comment by Saphrym** [comment]
Also... after the crash... I go back in and the structure has spawned... but the chest is empty.

**Comment by impiaaa** [comment]
Okay, thanks. I just verified that it is indeed my fault, and I'll try to get a bugfix release out.

**Comment by impiaaa** [comment]
Ok, fix is up on CurseForge: http://minecraft.curseforge.com/mc-mods/72733-myworldgen/files/2225308 Let me know if it works out for you

**Comment by Saphrym** [comment]
Will do! Thanks!
